#!/bin/bash
dir=$(pwd)/
file=masc
topFunct=execute

if [[ -z "${XLS}" ]]; then
  echo "\$XLS env var needs to be set to bazel-bin directory of XLS";
  exit 1;
fi

$XLS/xls/dslx/interpreter_main $dir$file.x
if [[ $(echo $?) -ne 0 ]]; then
  echo "Interpreter failure, unable to elaborate Verilog";
  exit 1;
else
  $XLS/xls/dslx/ir_convert/ir_converter_main --top=$topFunct $dir$file.x > $dir$file.ir;
  $XLS/xls/tools/opt_main $dir$file.ir > $dir$file.opt.ir;
  $XLS/xls/tools/codegen_main --generator=pipeline --pipeline_stages=5 --delay_model=sky130 --separate_lines $dir$file.opt.ir > __masc__execute.sv;
  sv2v --write=adjacent __masc__execute.sv;
  exit 0;
fi
