#!/bin/bash
log=check_all.out
fileList=$(ls -1 ../conversations/Zk*/utilized_code/*)

if [[ -z "${XLS}" ]]; then
  echo "\$XLS env var needs to be set to bazel-bin directory of XLS";
  exit 1;
fi

if [[ -e $log ]]; then
  rm $log;
fi

for f in $fileList; do
  $XLS/xls/dslx/interpreter_main $f # show user tests being run and passed/failed
  $XLS/xls/dslx/interpreter_main $f --alsologtostderr >> $log 2>&1 # for cosim logging
done
