#!/bin/bash
dir=$(pwd)/top_level/
file=masc
topFunct=execute

if [[ -z "${XLS}" ]]; then
  echo "\$XLS env var needs to be set to bazel-bin directory of XLS";
  exit 1;
fi

$XLS/xls/dslx/interpreter_main $dir$file.x
if [[ $(echo $?) -ne 0 ]]; then
  echo "Interpreter failure, unable to elaborate Verilog";
  exit 1;
else
  $XLS/xls/dslx/ir_convert/ir_converter_main --top=$topFunct $dir$file.x > $dir$file.ir;
  $XLS/xls/tools/opt_main $dir$file.ir > $dir$file.opt.ir;
  $XLS/xls/tools/codegen_main --generator=pipeline \
       #--clock_period_ps=1000 \
       --pipeline_stages=1   \
       --delay_model=sky130  \
       --separate_lines $dir$file.opt.ir > $dir$topFunct.v
fi
