###############################################################################
# Created by write_sdc
# Fri Sep  1 20:36:27 2023
###############################################################################
current_design user_proj_example
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 25.0000 [get_ports {wb_clk_i}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_clock_latency -source -min 4.6500 [get_clocks {clk}]
set_clock_latency -source -max 5.5700 [get_clocks {clk}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[0]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[0]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[10]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[10]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[11]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[11]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[12]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[12]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[13]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[13]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[14]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[14]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[15]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[15]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[16]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[16]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[17]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[17]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[18]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[18]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[19]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[19]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[1]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[1]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[20]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[20]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[21]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[21]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[22]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[22]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[23]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[23]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[24]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[24]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[25]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[25]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[26]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[26]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[27]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[27]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[28]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[28]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[29]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[29]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[2]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[2]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[30]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[30]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[31]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[31]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[32]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[32]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[33]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[33]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[34]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[34]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[35]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[35]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[36]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[36]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[37]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[37]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[38]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[38]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[39]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[39]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[3]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[3]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[40]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[40]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[41]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[41]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[42]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[42]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[43]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[43]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[44]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[44]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[45]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[45]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[46]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[46]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[47]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[47]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[48]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[48]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[49]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[49]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[4]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[4]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[50]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[50]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[51]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[51]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[52]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[52]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[53]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[53]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[54]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[54]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[55]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[55]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[56]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[56]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[57]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[57]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[58]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[58]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[59]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[59]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[5]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[5]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[60]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[60]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[61]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[61]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[62]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[62]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[63]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[63]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[64]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[64]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[65]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[65]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[66]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[66]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[67]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[67]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[68]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[68]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[69]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[69]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[6]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[6]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[70]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[70]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[71]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[71]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[72]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[72]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[73]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[73]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[74]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[74]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[75]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[75]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[76]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[76]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[77]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[77]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[78]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[78]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[79]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[79]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[7]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[7]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[80]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[80]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[81]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[81]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[82]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[82]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[83]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[83]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[84]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[84]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[85]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[85]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[86]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[86]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[87]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[87]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[88]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[88]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[89]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[89]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[8]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[8]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[90]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[90]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[91]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[91]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[92]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[92]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[93]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[93]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[94]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[94]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[95]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[95]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_in[9]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_in[9]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[0]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[0]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[10]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[10]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[11]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[11]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[12]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[12]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[13]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[13]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[14]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[14]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[15]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[15]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[16]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[16]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[17]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[17]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[18]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[18]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[19]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[19]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[1]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[1]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[20]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[20]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[21]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[21]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[22]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[22]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[23]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[23]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[24]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[24]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[25]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[25]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[26]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[26]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[27]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[27]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[28]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[28]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[29]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[29]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[2]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[2]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[30]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[30]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[31]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[31]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[32]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[32]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[3]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[3]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[4]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[4]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[5]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[5]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[6]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[6]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[7]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[7]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[8]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[8]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {la_data_out[9]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {la_data_out[9]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.1900 [get_ports {la_data_out[32]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[31]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[30]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[29]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[28]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[27]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[26]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[25]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[24]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[23]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[22]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[21]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[20]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[19]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[18]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[17]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[16]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[15]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[14]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[13]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[12]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[11]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[10]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[9]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[8]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[7]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[6]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[5]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[4]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[3]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[2]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[1]}]
set_load -pin_load 0.1900 [get_ports {la_data_out[0]}]
set_input_transition 0.6100 [get_ports {wb_clk_i}]
set_input_transition -min 0.0700 [get_ports {la_data_in[95]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[95]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[94]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[94]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[93]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[93]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[92]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[92]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[91]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[91]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[90]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[90]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[89]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[89]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[88]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[88]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[87]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[87]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[86]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[86]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[85]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[85]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[84]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[84]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[83]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[83]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[82]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[82]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[81]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[81]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[80]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[80]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[79]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[79]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[78]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[78]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[77]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[77]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[76]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[76]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[75]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[75]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[74]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[74]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[73]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[73]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[72]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[72]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[71]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[71]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[70]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[70]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[69]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[69]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[68]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[68]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[67]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[67]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[66]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[66]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[65]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[65]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[64]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[64]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[63]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[63]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[62]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[62]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[61]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[61]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[60]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[60]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[59]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[59]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[58]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[58]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[57]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[57]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[56]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[56]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[55]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[55]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[54]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[54]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[53]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[53]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[52]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[52]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[51]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[51]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[50]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[50]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[49]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[49]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[48]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[48]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[47]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[47]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[46]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[46]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[45]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[45]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[44]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[44]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[43]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[43]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[42]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[42]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[41]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[41]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[40]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[40]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[39]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[39]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[38]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[38]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[37]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[37]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[36]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[36]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[35]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[35]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[34]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[34]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[33]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[33]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[32]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[32]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[31]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[31]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[30]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[30]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[29]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[29]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[28]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[28]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[27]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[27]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[26]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[26]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[25]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[25]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[24]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[24]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[23]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[23]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[22]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[22]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[21]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[21]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[20]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[20]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[19]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[19]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[18]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[18]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[17]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[17]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[16]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[16]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[15]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[15]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[14]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[14]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[13]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[13]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[12]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[12]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[11]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[11]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[10]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[10]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[9]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[9]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[8]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[8]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[7]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[7]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[6]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[6]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[5]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[5]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[4]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[4]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[3]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[3]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[2]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[2]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[1]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[1]}]
set_input_transition -min 0.0700 [get_ports {la_data_in[0]}]
set_input_transition -max 0.8600 [get_ports {la_data_in[0]}]
set_timing_derate -early 0.9500
set_timing_derate -late 1.0500
###############################################################################
# Design Rules
###############################################################################
set_max_transition 1.0000 [current_design]
set_max_fanout 16.0000 [current_design]
